/** Dates transcribed from calendario.html. Confirm against the official decree before publishing. */
export const electoralCalendar = [
  {
    date: "06 OCT",
    iso: "2026-10-06",
    category: "CONVOCATORIA",
    title: "Disolución y convocatoria",
    text: "El punto de partida del calendario electoral y de la renovación de las Cortes.",
    color: "#c2dc9d",
  },
  {
    date: "21–26 OCT",
    iso: "2026-10-21",
    end: "2026-10-26",
    category: "CANDIDATURAS",
    title: "Presentación de listas",
    text: "Periodo de presentación de las candidaturas que concurrirán a las elecciones.",
    color: "#b4b8ad",
  },
  {
    date: "02 NOV",
    iso: "2026-11-02",
    category: "CANDIDATURAS",
    title: "Proclamación de candidatos",
    text: "Las juntas electorales proclaman las candidaturas.",
    color: "#b4b8ad",
  },
  {
    date: "13–27 NOV",
    iso: "2026-11-13",
    end: "2026-11-27",
    category: "CAMPAÑA",
    title: "Campaña electoral",
    text: "Quince días de campaña para conocer las propuestas de los partidos.",
    color: "#ef939b",
  },
  {
    date: "19 NOV",
    iso: "2026-11-19",
    category: "VOTO POR CORREO",
    title: "Fin de la solicitud del voto por correo",
    text: "Fecha prevista como último día para solicitar el voto por correo.",
    color: "#e8c36b",
  },
  {
    date: "23 NOV",
    iso: "2026-11-23",
    category: "ENCUESTAS",
    title: "Último día para publicar sondeos",
    text: "Última fecha de publicación de encuestas electorales antes de la votación.",
    color: "#91bce6",
  },
  {
    date: "24 NOV",
    iso: "2026-11-24",
    category: "VOTO DESDE EL EXTRANJERO",
    title: "CERA: fin del voto por correo",
    text: "Fin del plazo previsto para enviar el voto por correo desde el extranjero para personas inscritas en el CERA.",
    color: "#e8d79d",
  },
  {
    date: "25 NOV",
    iso: "2026-11-25",
    category: "VOTO POR CORREO",
    title: "Fin del envío del voto por correo",
    text: "Último día previsto para enviar el voto por correo en España.",
    color: "#e8c36b",
  },
  {
    date: "26 NOV",
    iso: "2026-11-26",
    category: "VOTO DESDE EL EXTRANJERO",
    title: "CERA: fin del voto en urna",
    text: "Fin del plazo previsto para depositar el voto en urna en el extranjero para personas inscritas en el CERA.",
    color: "#e8d79d",
  },
  {
    date: "28 NOV",
    iso: "2026-11-28",
    category: "REFLEXIÓN",
    title: "Jornada de reflexión",
    text: "El día previo a las elecciones, una vez finalizada la campaña electoral.",
    color: "#f1f2e9",
  },
  {
    date: "29 NOV",
    iso: "2026-11-29",
    category: "LAS URNAS",
    title: "Elecciones Generales",
    text: "La jornada de votación para elegir a los representantes del Congreso y del Senado.",
    color: "#c2dc9d",
    featured: true,
  },
  {
    date: "04–07 DIC",
    iso: "2026-12-04",
    end: "2026-12-07",
    category: "ESCRUTINIO",
    title: "Escrutinio general y voto CERA",
    text: "Periodo previsto para el escrutinio general y el voto CERA, según el boceto facilitado.",
    color: "#e8d79d",
  },
  {
    date: "24 DIC",
    iso: "2026-12-24",
    category: "DESPUÉS DE LAS ELECCIONES",
    title: "Límite para constituir las Cortes",
    text: "Fecha límite prevista para la constitución de las nuevas Cortes.",
    color: "#91bce6",
  },
];
