import type { Locale } from '../locales';
export const pollsPath = (locale: Locale) => locale === 'es' ? '/encuestas' : `/${locale}/encuestas`;
export const pollCopy = {
  es: {
    remainingVotes: 'Resto del voto publicado', comparisonGrouping: 'Para ponderar se conservan los partidos desglosados por todas las fuentes y se suma el resto de sus categorías publicadas antes de calcular la media. Los escaños no se promedian.', originalVote: 'Gráfico original de voto · JPG', originalTransfer: 'Gráfico original de trasvase · JPG', articlePublication: 'Consultar la publicación del medio',
    currentOnly: 'Estimación de voto', currentOnlyDescription: 'Porcentajes de voto publicados por las fuentes seleccionadas. El arco representa voto, no escaños.', publishedTotal: 'Total publicado',
    noData: 'Sin datos para las fuentes seleccionadas',
    noDataDescription: 'Las encuestadoras seleccionadas no publican información para esta gráfica en el periodo mostrado. Activa otra fuente para consultarla.',
    otherParties: 'Otros partidos',
    incompleteEstimate: 'Los porcentajes publicados no suman el 100 %. El espacio sin color conserva esa diferencia, sin asignarla a ninguna candidatura.',
    noHistorical: 'Sin resultado histórico publicado por las fuentes seleccionadas.',
    periodSelection: 'Se muestra el periodo más reciente de la selección; las encuestas de meses distintos no se ponderan juntas.',
    publishedJson: 'Datos publicados · JSON',
    publishedTsv: 'Estimación publicada · TSV',
    commissionedFor: 'Encuesta elaborada para',
    originalPublication: 'Consultar la publicación original',
    seatNote: 'Escaños publicados entre paréntesis; el arco representa porcentajes de voto.',

    sourceContext: 'Encuesta elaborada por 40dB. para EL PAÍS y la Cadena SER. Los archivos originales proceden de la publicación de datos internos del barómetro de octubre de 2026.', sourcePublication: 'Consultar la publicación original en EL PAÍS',
    current: 'Estimación de voto actual y resultado del 23J', currentDescription: 'Arco exterior: estimación actual. Arco interior: generales del 23 de julio de 2023. Porcentajes sobre votos válidos, según las fuentes seleccionadas; los arcos no representan escaños.', currentSeries: 'Estimación actual', electionSeries: 'Generales · 23J de 2023', electoralOther: 'Otros + blanco', voteReport: 'Informe electoral · PDF',
    methodologyTitle: 'Metodología por encuestadora',
    sex: 'Intención de voto por sexo', sexDescription: 'Intención directa de voto en % de encuestados de cada sexo. Etiquetas redondeadas; cifras con un decimal en el tooltip y la tabla.', men: 'Hombres', women: 'Mujeres',
    regional: 'Nacionalistas y regionales', otherResponses: 'Otros*', ageTotal: 'Total', ageNote: '*Otros incluye otros partidos, voto en blanco y nulo, abstención, indecisos y quienes prefieren no contestar. Las agrupaciones suman los porcentajes publicados; no se estiman celdas vacías ni se ajustan las barras al 100 %. Los totales pueden variar por redondeo.',
    breadcrumbHome: 'Inicio', breadcrumbCurrent: 'Encuestas', breadcrumbLabel: 'Ruta de navegación',
    selected: 'Se muestran cinco partidos; todas las respuestas están en la tabla.',
    link: 'Ver todas las gráficas', title: 'Las encuestas, en detalle', intro: 'Participación, cambios de voto y diferencias por edad y sexo. Datos publicados por las encuestadoras disponibles.',
    kicker: 'EL PULSO ELECTORAL', total: 'Población general', turnout: '¿Quién acudiría a votar?', turnoutDescription: 'Porcentaje que responde 10: con toda seguridad iría a votar. Grupos según recuerdo de voto en las generales de 2023.',
    age: 'Intención de voto en cada grupo de edad', ageDescription: 'Intención directa de voto sobre el total de cada grupo de edad. Una barra por grupo, dividida en categorías de respuesta. Etiquetas redondeadas; cifras con un decimal en el tooltip y la tabla.',
    transfer: '¿Qué votarían ahora?', transferDescription: 'Intención directa de voto según el partido que recuerdan haber votado en 2023. Cada columna representa un grupo de votantes.',
    data: 'Consultar los datos', response: 'Respuesta', missing: 'Sin dato publicado', methods: 'Cómo leer estas gráficas',
    note: 'La intención directa recoge las respuestas de la encuesta. La estimación electoral de la portada aplica el modelo de la encuestadora y usa el voto válido como base. Son medidas diferentes.',
    weighting: 'La única encuestadora disponible es 40dB., con un peso del 100 %. Sus tablas ya incluyen la ponderación de la muestra. Cuando haya varias encuestadoras, se combinarán únicamente preguntas, respuestas, grupos y periodos comparables mediante la media ponderada Σ(peso × porcentaje) / Σ(peso). Los datos ausentes quedan fuera del cálculo.',
    technical: '2.000 entrevistas online (CAWI). Trabajo de campo del 25 al 28 de septiembre de 2026. Población adulta residente en España, excepto Ceuta y Melilla. Error indicado por la fuente: ±2,2 puntos al 95 % de confianza para el total de la muestra; no para cada subgrupo.',
    rounding: 'Porcentajes publicados con un decimal. Las celdas vacías se conservan como datos no publicados. Los totales pueden variar por redondeo.',
    sources: 'Fuentes y descargas', tables: 'Tablas originales · XLSX', methodology: 'Nota metodológica · PDF', csv: 'Datos de las gráficas · CSV', sourceNote: 'Fuente: 40dB. · Octubre de 2026', recall: 'Recuerdo de voto en 2023', ageGroup: 'Edad',
  },
  gl: {
    remainingVotes: 'Resto do voto publicado', comparisonGrouping: 'Para ponderar consérvanse os partidos desagregados por todas as fontes e súmase o resto das súas categorías publicadas antes de calcular a media. Os escanos non se promedian.', originalVote: 'Gráfico orixinal de voto · JPG', originalTransfer: 'Gráfico orixinal de transferencia · JPG', articlePublication: 'Consultar a publicación do medio',
    currentOnly: 'Estimación de voto', currentOnlyDescription: 'Porcentaxes de voto publicadas polas fontes seleccionadas. O arco representa voto, non escanos.', publishedTotal: 'Total publicado',
    noData: 'Sen datos para as fontes seleccionadas',
    noDataDescription: 'As enquisadoras seleccionadas non publican información para esta gráfica no período mostrado. Activa outra fonte para consultala.',
    otherParties: 'Outros partidos',
    incompleteEstimate: 'As porcentaxes publicadas non suman o 100 %. O espazo sen cor conserva esa diferenza, sen asignala a ningunha candidatura.',
    noHistorical: 'Sen resultado histórico publicado polas fontes seleccionadas.',
    periodSelection: 'Móstrase o período máis recente da selección; as enquisas de meses distintos non se ponderan xuntas.',
    publishedJson: 'Datos publicados · JSON',
    publishedTsv: 'Estimación publicada · TSV',
    commissionedFor: 'Enquisa elaborada para',
    originalPublication: 'Consultar a publicación orixinal',
    seatNote: 'Escanos publicados entre parénteses; o arco representa porcentaxes de voto.',

    sourceContext: 'Enquisa elaborada por 40dB. para EL PAÍS e a Cadena SER. Os arquivos orixinais proceden da publicación de datos internos do barómetro de outubro de 2026.', sourcePublication: 'Consultar a publicación orixinal en EL PAÍS',
    current: 'Estimación de voto actual e resultado do 23X', currentDescription: 'Arco exterior: estimación actual. Arco interior: xerais do 23 de xullo de 2023. Porcentaxes sobre votos válidos, segundo as fontes seleccionadas; os arcos non representan escanos.', currentSeries: 'Estimación actual', electionSeries: 'Xerais · 23X de 2023', electoralOther: 'Outros + branco', voteReport: 'Informe electoral · PDF',
    methodologyTitle: 'Metodoloxía por enquisadora',
    sex: 'Intención de voto por sexo', sexDescription: 'Intención directa de voto en % das persoas enquisadas de cada sexo. Etiquetas arredondadas; cifras cun decimal no tooltip e na táboa.', men: 'Homes', women: 'Mulleres',
    regional: 'Nacionalistas e rexionais', otherResponses: 'Outros*', ageTotal: 'Total', ageNote: '*Outros inclúe outros partidos, voto en branco e nulo, abstención, indecisos e quen prefire non contestar. As agrupacións suman as porcentaxes publicadas; non se estiman celas baleiras nin se axustan as barras ao 100 %. Os totais poden variar polo arredondamento.',
    breadcrumbHome: 'Inicio', breadcrumbCurrent: 'Enquisas', breadcrumbLabel: 'Ruta de navegación',
    selected: 'Móstranse cinco partidos; todas as respostas están na táboa.',
    link: 'Ver todas as gráficas', title: 'As enquisas, en detalle', intro: 'Participación, cambios de voto e diferenzas por idade e sexo. Datos publicados polas enquisadoras dispoñibles.',
    kicker: 'O PULSO ELECTORAL', total: 'Poboación xeral', turnout: 'Quen acudiría a votar?', turnoutDescription: 'Porcentaxe que responde 10: con toda seguridade iría a votar. Grupos segundo lembranza de voto nas xerais de 2023.',
    age: 'Intención de voto en cada grupo de idade', ageDescription: 'Intención directa de voto sobre o total de cada grupo de idade. Unha barra por grupo, dividida en categorías de resposta. Etiquetas arredondadas; cifras cun decimal no tooltip e na táboa.',
    transfer: 'Que votarían agora?', transferDescription: 'Intención directa de voto segundo o partido que lembran votar en 2023. Cada columna representa un grupo de votantes.',
    data: 'Consultar os datos', response: 'Resposta', missing: 'Sen dato publicado', methods: 'Como ler estas gráficas',
    note: 'A intención directa recolle as respostas da enquisa. A estimación electoral da portada aplica o modelo da enquisadora e usa o voto válido como base. Son medidas diferentes.',
    weighting: 'A única enquisadora dispoñible é 40dB., cun peso do 100 %. As súas táboas xa inclúen a ponderación da mostra. Con varias enquisadoras, combinaranse só preguntas, respostas, grupos e períodos comparables coa media ponderada Σ(peso × porcentaxe) / Σ(peso). Os datos ausentes quedan fóra do cálculo.',
    technical: '2.000 entrevistas online (CAWI). Traballo de campo do 25 ao 28 de setembro de 2026. Poboación adulta residente en España, agás Ceuta e Melilla. Erro indicado pola fonte: ±2,2 puntos ao 95 % de confianza para a mostra total; non para cada subgrupo.',
    rounding: 'Porcentaxes publicadas cun decimal. As celas baleiras consérvanse como datos non publicados. Os totais poden variar polo arredondamento.',
    sources: 'Fontes e descargas', tables: 'Táboas orixinais · XLSX', methodology: 'Nota metodolóxica · PDF', csv: 'Datos das gráficas · CSV', sourceNote: 'Fonte: 40dB. · Outubro de 2026', recall: 'Lembranza de voto en 2023', ageGroup: 'Idade',
  },
  ca: {
    remainingVotes: 'Resta del vot publicat', comparisonGrouping: 'Per ponderar es conserven els partits desglossats per totes les fonts i se suma la resta de les seves categories publicades abans de calcular la mitjana. Els escons no es promitgen.', originalVote: 'Gràfic original de vot · JPG', originalTransfer: 'Gràfic original de transvasament · JPG', articlePublication: 'Consultar la publicació del mitjà',
    currentOnly: 'Estimació de vot', currentOnlyDescription: 'Percentatges de vot publicats per les fonts seleccionades. L’arc representa vot, no escons.', publishedTotal: 'Total publicat',
    noData: 'Sense dades per a les fonts seleccionades',
    noDataDescription: 'Les enquestadores seleccionades no publiquen informació per a aquesta gràfica en el període mostrat. Activa una altra font per consultar-la.',
    otherParties: 'Altres partits',
    incompleteEstimate: 'Els percentatges publicats no sumen el 100 %. L’espai sense color conserva aquesta diferència, sense assignar-la a cap candidatura.',
    noHistorical: 'Sense resultat històric publicat per les fonts seleccionades.',
    periodSelection: 'Es mostra el període més recent de la selecció; les enquestes de mesos diferents no es ponderen juntes.',
    publishedJson: 'Dades publicades · JSON',
    publishedTsv: 'Estimació publicada · TSV',
    commissionedFor: 'Enquesta elaborada per a',
    originalPublication: 'Consultar la publicació original',
    seatNote: 'Escons publicats entre parèntesis; l’arc representa percentatges de vot.',

    sourceContext: 'Enquesta elaborada per 40dB. per a EL PAÍS i la Cadena SER. Els arxius originals provenen de la publicació de dades internes del baròmetre d’octubre de 2026.', sourcePublication: 'Consultar la publicació original a EL PAÍS',
    current: 'Estimació de vot actual i resultat del 23J', currentDescription: 'Arc exterior: estimació actual. Arc interior: generals del 23 de juliol de 2023. Percentatges sobre vots vàlids, segons les fonts seleccionades; els arcs no representen escons.', currentSeries: 'Estimació actual', electionSeries: 'Generals · 23J de 2023', electoralOther: 'Altres + blanc', voteReport: 'Informe electoral · PDF',
    methodologyTitle: 'Metodologia per enquestadora',
    sex: 'Intenció de vot per sexe', sexDescription: 'Intenció directa de vot en % d’enquestats de cada sexe. Etiquetes arrodonides; xifres amb un decimal al tooltip i a la taula.', men: 'Homes', women: 'Dones',
    regional: 'Nacionalistes i regionals', otherResponses: 'Altres*', ageTotal: 'Total', ageNote: '*Altres inclou altres partits, vot en blanc i nul, abstenció, indecisos i qui prefereix no contestar. Les agrupacions sumen els percentatges publicats; no s’estimen cel·les buides ni s’ajusten les barres al 100 %. Els totals poden variar per arrodoniment.',
    breadcrumbHome: 'Inici', breadcrumbCurrent: 'Enquestes', breadcrumbLabel: 'Ruta de navegació',
    selected: 'Es mostren cinc partits; totes les respostes són a la taula.',
    link: 'Veure totes les gràfiques', title: 'Les enquestes, en detall', intro: 'Participació, canvis de vot i diferències per edat i sexe. Dades publicades per les enquestadores disponibles.',
    kicker: 'EL POLS ELECTORAL', total: 'Població general', turnout: 'Qui aniria a votar?', turnoutDescription: 'Percentatge que respon 10: amb tota seguretat aniria a votar. Grups segons record de vot a les generals de 2023.',
    age: 'Intenció de vot en cada grup d’edat', ageDescription: 'Intenció directa de vot sobre el total de cada grup d’edat. Una barra per grup, dividida en categories de resposta. Etiquetes arrodonides; xifres amb un decimal al tooltip i a la taula.',
    transfer: 'Què votarien ara?', transferDescription: 'Intenció directa de vot segons el partit que recorden haver votat el 2023. Cada columna representa un grup de votants.',
    data: 'Consultar les dades', response: 'Resposta', missing: 'Sense dada publicada', methods: 'Com llegir aquestes gràfiques',
    note: 'La intenció directa recull les respostes de l’enquesta. L’estimació electoral de la portada aplica el model de l’enquestadora i usa el vot vàlid com a base. Són mesures diferents.',
    weighting: 'L’única enquestadora disponible és 40dB., amb un pes del 100 %. Les seves taules ja inclouen la ponderació de la mostra. Amb diverses enquestadores, es combinaran només preguntes, respostes, grups i períodes comparables amb la mitjana ponderada Σ(pes × percentatge) / Σ(pes). Les dades absents queden fora del càlcul.',
    technical: '2.000 entrevistes online (CAWI). Treball de camp del 25 al 28 de setembre de 2026. Població adulta resident a Espanya, excepte Ceuta i Melilla. Error indicat per la font: ±2,2 punts al 95 % de confiança per a la mostra total; no per a cada subgrup.',
    rounding: 'Percentatges publicats amb un decimal. Les cel·les buides es conserven com a dades no publicades. Els totals poden variar per arrodoniment.',
    sources: 'Fonts i descàrregues', tables: 'Taules originals · XLSX', methodology: 'Nota metodològica · PDF', csv: 'Dades de les gràfiques · CSV', sourceNote: 'Font: 40dB. · Octubre de 2026', recall: 'Record de vot el 2023', ageGroup: 'Edat',
  },
  eu: {
    remainingVotes: 'Argitaratutako gainerako botoa', comparisonGrouping: 'Haztatzeko, iturri guztiek bereizitako alderdiak mantentzen dira eta gainerako kategoria argitaratuak batzen dira batezbestekoa kalkulatu aurretik. Eserlekuak ez dira batezbestekoan sartzen.', originalVote: 'Jatorrizko boto grafikoa · JPG', originalTransfer: 'Jatorrizko boto aldaketa grafikoa · JPG', articlePublication: 'Ikusi hedabidearen argitalpena',
    currentOnly: 'Boto estimazioa', currentOnlyDescription: 'Hautatutako iturriek argitaratutako boto ehunekoak. Arkuak botoa adierazten du, ez eserlekuak.', publishedTotal: 'Argitaratutako guztizkoa',
    noData: 'Ez dago daturik hautatutako iturrietarako',
    noDataDescription: 'Hautatutako inkesta etxeek ez dute grafiko honetarako informaziorik argitaratzen erakutsitako aldian. Hautatu beste iturri bat.',
    otherParties: 'Beste alderdiak',
    incompleteEstimate: 'Argitaratutako ehunekoek ez dute % 100 batzen. Kolorerik gabeko tarteak alde hori gordetzen du, hautagaitza bati esleitu gabe.',
    noHistorical: 'Hautatutako iturriek ez dute emaitza historikorik argitaratu.',
    periodSelection: 'Hautaketako azken aldia erakusten da; hilabete desberdinetako inkestak ez dira batera haztatzen.',
    publishedJson: 'Argitaratutako datuak · JSON',
    publishedTsv: 'Argitaratutako estimazioa · TSV',
    commissionedFor: 'Inkesta hedabide hauentzat egina',
    originalPublication: 'Ikusi jatorrizko argitalpena',
    seatNote: 'Argitaratutako eserlekuak parentesi artean; arkuak boto ehunekoak erakusten ditu.',

    sourceContext: '40dB.k EL PAÍS eta Cadena SER hedabideentzat egindako inkesta. Jatorrizko fitxategiak 2026ko urriko barometroaren barne datuen argitalpenetik datoz.', sourcePublication: 'Ikusi jatorrizko argitalpena EL PAÍSen',
    current: 'Egungo boto estimazioa eta uztailaren 23ko emaitza', currentDescription: 'Kanpoko arkua: egungo estimazioa. Barruko arkua: 2023ko uztailaren 23ko hauteskunde orokorrak. Baliozko botoen ehunekoak, hautatutako iturrien arabera; arkuek ez dituzte eserlekuak adierazten.', currentSeries: 'Egungo estimazioa', electionSeries: 'Orokorrak · 2023-07-23', electoralOther: 'Besteak + zuriak', voteReport: 'Hauteskunde txostena · PDF',
    methodologyTitle: 'Metodologia inkesta etxearen arabera',
    sex: 'Boto asmoa sexuaren arabera', sexDescription: 'Zuzeneko boto asmoa sexu bakoitzeko inkestatuen ehunekoetan. Etiketak biribilduta; hamartar bat tooltip-ean eta taulan.', men: 'Gizonak', women: 'Emakumeak',
    regional: 'Nazionalistak eta eskualdekoak', otherResponses: 'Besteak*', ageTotal: 'Guztira', ageNote: '*Besteak kategoriak beste alderdiak, boto zuriak eta baliogabeak, abstentzioa, zalantzatiak eta erantzun nahi ez dutenak biltzen ditu. Taldeek argitaratutako ehunekoak batzen dituzte; ez dira gelaxka hutsak estimatzen eta barrak ez dira % 100era doitzen. Guztizkoak biribiltzearen ondorioz alda daitezke.',
    breadcrumbHome: 'Hasiera', breadcrumbCurrent: 'Inkestak', breadcrumbLabel: 'Nabigazio bidea',
    selected: 'Bost alderdi erakusten dira; erantzun guztiak taulan daude.',
    link: 'Ikusi grafiko guztiak', title: 'Inkestak, xehetasunez', intro: 'Parte-hartzea, boto aldaketak eta adinaren eta sexuaren araberako aldeak. Eskuragarri dauden inkesta etxeen datu argitaratuak.',
    kicker: 'HAUTESKUNDEEN PULTSUA', total: 'Biztanleria orokorra', turnout: 'Nor joango litzateke bozkatzera?', turnoutDescription: '10 erantzuten dutenen ehunekoa: ziurtasun osoz bozkatuko lukete. Taldeak 2023ko hauteskundeetako boto oroitzapenaren arabera.',
    age: 'Boto asmoa adin talde bakoitzean', ageDescription: 'Zuzeneko boto asmoa, adin talde bakoitzaren guztizkoaren gainean. Barra bat talde bakoitzeko, erantzun kategorietan banatuta. Etiketak biribilduta; hamartar bat tooltip-ean eta taulan.',
    transfer: 'Zer bozkatuko lukete orain?', transferDescription: 'Zuzeneko boto asmoa, 2023an bozkatu zutela gogoratzen duten alderdiaren arabera. Zutabe bakoitza boto emaileen talde bat da.',
    data: 'Kontsultatu datuak', response: 'Erantzuna', missing: 'Argitaratutako daturik ez', methods: 'Nola irakurri grafiko hauek',
    note: 'Zuzeneko asmoak inkestako erantzunak jasotzen ditu. Azaleko hauteskunde estimazioak inkesta etxearen eredua aplikatzen du eta baliozko botoa erabiltzen du oinarri gisa. Neurri desberdinak dira.',
    weighting: 'Eskuragarri dagoen inkesta etxe bakarra 40dB. da, % 100eko pisuarekin. Taulek laginaren haztapena jasotzen dute. Inkesta etxe gehiago daudenean, galdera, erantzun, talde eta aldi konparagarriak soilik bateratuko dira batezbesteko haztatuarekin: Σ(pisua × ehunekoa) / Σ(pisua). Falta diren datuak kalkulutik kanpo geratzen dira.',
    technical: '2.000 online elkarrizketa (CAWI). Landa lana 2026ko irailaren 25etik 28ra. Espainian bizi diren helduak, Ceuta eta Melilla izan ezik. Iturriak adierazitako errorea: ±2,2 puntu, % 95eko konfiantzarekin, lagin osorako; ez azpitalde bakoitzerako.',
    rounding: 'Ehunekoak hamartar batekin argitaratu dira. Gelaxka hutsak argitaratu gabeko datu gisa mantentzen dira. Guztizkoak biribiltzearen ondorioz alda daitezke.',
    sources: 'Iturriak eta deskargak', tables: 'Jatorrizko taulak · XLSX', methodology: 'Metodologia oharra · PDF', csv: 'Grafikoetako datuak · CSV', sourceNote: 'Iturria: 40dB. · 2026ko urria', recall: '2023ko boto oroitzapena', ageGroup: 'Adina',
  },
} satisfies Record<Locale, Record<string, string>>;
export function responseLabel(response: string, locale: Locale) {
  const translations: Record<string, string[]> = {
    'Otro': ['Otro', 'Outro', 'Altres', 'Beste bat'],
    'Votaría en blanco': ['Votaría en blanco', 'Votaría en branco', 'Votaria en blanc', 'Boto zuria'],
    'Votaría nulo': ['Votaría nulo', 'Votaría nulo', 'Votaria nul', 'Boto baliogabea'],
    'No votaría': ['No votaría', 'Non votaría', 'No votaria', 'Ez luke bozkatuko'],
    'No lo sé': ['No lo sé', 'Non o sei', 'No ho sé', 'Ez dakit'],
    'Prefiero no contestar': ['Prefiero no contestar', 'Prefiro non contestar', 'Prefereixo no contestar', 'Nahiago dut ez erantzun'],
  };
  return translations[response]?.[['es','gl','ca','eu'].indexOf(locale)] ?? response.split(' (')[0];
}
