import type { Locale } from '../locales';
export const insightsCopy = {
  es: { scroll: 'Desliza la gráfica para ver la barra completa →', rejection: 'Rechazo a los partidos', rejectionDescription: 'Porcentaje que responde «0: no le votaría nunca» para cada partido. Base: población encuestada, no solo sus votantes.', sympathy: 'Simpatía frente a intención de voto', sympathyDescription: 'Simpatía (P4, barra clara) e intención directa de voto (P3, barra sólida), sobre el total de encuestados. Se muestran seis partidos; todas las respuestas están en las tablas.', sympathySeries: 'Simpatía', intentionSeries: 'Intención directa', ideology: 'Voto según ideología', ideologyDescription: 'Intención directa de voto según la ideología declarada. Cada barra representa el total de su grupo.', generation: 'Voto por generación y sexo', generationDescription: 'Intención directa de voto en cada combinación de generación y sexo. Baby Boomers y Silent Generation aparecen juntos en la fuente. Cada barra tiene como base su propio grupo.', unknown: 'No lo sé' },
  gl: { scroll: 'Despraza a gráfica para ver a barra completa →', rejection: 'Rexeitamento dos partidos', rejectionDescription: 'Porcentaxe que responde «0: nunca o votaría» para cada partido. Base: poboación enquisada, non só os seus votantes.', sympathy: 'Simpatía fronte a intención de voto', sympathyDescription: 'Simpatía (P4, barra clara) e intención directa (P3, barra sólida), sobre o total de enquisados. Móstranse seis partidos; todas as respostas están nas táboas.', sympathySeries: 'Simpatía', intentionSeries: 'Intención directa', ideology: 'Voto segundo a ideoloxía', ideologyDescription: 'Intención directa segundo a ideoloxía declarada. Cada barra representa o total do seu grupo.', generation: 'Voto por xeración e sexo', generationDescription: 'Intención directa en cada combinación de xeración e sexo. Baby Boomers e Silent Generation aparecen xuntos na fonte. Cada barra ten como base o seu propio grupo.', unknown: 'Non o sei' },
  ca: { scroll: 'Desplaça la gràfica per veure la barra completa →', rejection: 'Rebuig dels partits', rejectionDescription: 'Percentatge que respon «0: no el votaria mai» per a cada partit. Base: població enquestada, no només els seus votants.', sympathy: 'Simpatia davant la intenció de vot', sympathyDescription: 'Simpatia (P4, barra clara) i intenció directa (P3, barra sòlida), sobre el total d’enquestats. Es mostren sis partits; totes les respostes són a les taules.', sympathySeries: 'Simpatia', intentionSeries: 'Intenció directa', ideology: 'Vot segons ideologia', ideologyDescription: 'Intenció directa segons la ideologia declarada. Cada barra representa el total del seu grup.', generation: 'Vot per generació i sexe', generationDescription: 'Intenció directa en cada combinació de generació i sexe. Baby Boomers i Silent Generation apareixen junts a la font. Cada barra té com a base el seu propi grup.', unknown: 'No ho sé' },
  eu: { scroll: 'Mugitu grafikoa barra osoa ikusteko →', rejection: 'Alderdien aurkako arbuioa', rejectionDescription: 'Alderdi bakoitzarentzat «0: ez nuke inoiz bozkatuko» erantzuten dutenen ehunekoa. Oinarria: inkestatutako biztanleria osoa.', sympathy: 'Begikotasuna eta boto asmoa', sympathyDescription: 'Begikotasuna (P4, barra argia) eta zuzeneko boto asmoa (P3, barra sendoa), inkestatu guztien gainean. Sei alderdi erakusten dira; erantzun guztiak tauletan daude.', sympathySeries: 'Begikotasuna', intentionSeries: 'Zuzeneko asmoa', ideology: 'Botoa ideologiaren arabera', ideologyDescription: 'Zuzeneko boto asmoa adierazitako ideologiaren arabera. Barra bakoitzak bere talde osoa adierazten du.', generation: 'Botoa belaunaldiaren eta sexuaren arabera', generationDescription: 'Zuzeneko asmoa belaunaldi eta sexu konbinazio bakoitzean. Iturriak Baby Boomers eta Silent Generation batera erakusten ditu. Barra bakoitzaren oinarria bere taldea da.', unknown: 'Ez dakit' },
} satisfies Record<Locale, Record<string, string>>;
export const ideologyLabels: Record<Locale, string[]> = {
  es: ['Extrema izquierda','Izquierda','Centro-izquierda','Centro','Centro-derecha','Derecha','Extrema derecha','No lo sé'],
  gl: ['Extrema esquerda','Esquerda','Centro-esquerda','Centro','Centro-dereita','Dereita','Extrema dereita','Non o sei'],
  ca: ['Extrema esquerra','Esquerra','Centre-esquerra','Centre','Centre-dreta','Dreta','Extrema dreta','No ho sé'],
  eu: ['Ezker muturra','Ezkerra','Zentro-ezkerra','Zentroa','Zentro-eskuina','Eskuina','Eskuin muturra','Ez dakit'],
};
